services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${Sa_Password:-<PASSWORD-HERE>}
        - MSSQL_PID=Developer
      ports:
        - 1433:1433
      restart: always
      healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:<PASSWORD-HERE>} -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P ${Sa_Password:<PASSWORD-HERE>} -d master -i docker-entrypoint-initdb.d/init-script.sql;
      '